# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'apr9.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1258, 721)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.myLogo = QtWidgets.QLabel(self.centralwidget)
        self.myLogo.setGeometry(QtCore.QRect(50, 10, 281, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.myLogo.setFont(font)
        self.myLogo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.myLogo.setLineWidth(0)
        self.myLogo.setText("")
        self.myLogo.setPixmap(QtGui.QPixmap(":/newicon/icons/nott.png"))
        self.myLogo.setObjectName("myLogo")
        self.myCall = QtWidgets.QPushButton(self.centralwidget)
        self.myCall.setGeometry(QtCore.QRect(50, 130, 281, 141))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.myCall.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newicon/icons/trent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.myCall.setIcon(icon)
        self.myCall.setIconSize(QtCore.QSize(40, 40))
        self.myCall.setObjectName("myCall")
        self.myHome = QtWidgets.QPushButton(self.centralwidget)
        self.myHome.setGeometry(QtCore.QRect(50, 300, 281, 141))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.myHome.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newicon/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.myHome.setIcon(icon1)
        self.myHome.setIconSize(QtCore.QSize(40, 40))
        self.myHome.setObjectName("myHome")
        self.myManual = QtWidgets.QPushButton(self.centralwidget)
        self.myManual.setGeometry(QtCore.QRect(950, 315, 231, 171))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.myManual.setFont(font)
        self.myManual.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newicon/icons/control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.myManual.setIcon(icon2)
        self.myManual.setIconSize(QtCore.QSize(150, 150))
        self.myManual.setObjectName("myManual")
        self.widget = QRoundProgressBar(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(490, 140, 261, 221))
        self.widget.setObjectName("widget")
        self.myStop = QtWidgets.QPushButton(self.centralwidget)
        self.myStop.setGeometry(QtCore.QRect(950, 130, 231, 171))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.myStop.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.myStop.setFont(font)
        self.myStop.setStyleSheet("")
        self.myStop.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newicon/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.myStop.setIcon(icon3)
        self.myStop.setIconSize(QtCore.QSize(1000, 1000))
        self.myStop.setObjectName("myStop")
        self.myTime = QtWidgets.QLabel(self.centralwidget)
        self.myTime.setGeometry(QtCore.QRect(950, 50, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.myTime.setFont(font)
        self.myTime.setObjectName("myTime")
        self.myMission = QtWidgets.QLabel(self.centralwidget)
        self.myMission.setGeometry(QtCore.QRect(460, 20, 341, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.myMission.sizePolicy().hasHeightForWidth())
        self.myMission.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.myMission.setFont(font)
        self.myMission.setObjectName("myMission")
        self.myBatteryLevel = QtWidgets.QLabel(self.centralwidget)
        self.myBatteryLevel.setGeometry(QtCore.QRect(530, 110, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.myBatteryLevel.setFont(font)
        self.myBatteryLevel.setObjectName("myBatteryLevel")
        self.myReset = QtWidgets.QPushButton(self.centralwidget)
        self.myReset.setGeometry(QtCore.QRect(50, 470, 281, 141))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.myReset.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../Downloads/reset-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.myReset.setIcon(icon4)
        self.myReset.setIconSize(QtCore.QSize(40, 40))
        self.myReset.setObjectName("myReset")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(360, 370, 561, 241))
        self.widget_2.setObjectName("widget_2")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 561, 241))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 559, 239))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 561, 241))
        self.label_2.setObjectName("label_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.myExit = QtWidgets.QPushButton(self.centralwidget)
        self.myExit.setGeometry(QtCore.QRect(1170, 0, 91, 61))
        self.myExit.setObjectName("myExit")
        self.myDesc = QtWidgets.QLabel(self.centralwidget)
        self.myDesc.setGeometry(QtCore.QRect(950, 500, 231, 111))
        self.myDesc.setFrameShape(QtWidgets.QFrame.Box)
        self.myDesc.setObjectName("myDesc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1258, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.myCall.setText(_translate("MainWindow", " TRENT"))
        self.myHome.setText(_translate("MainWindow", " HOME"))
        self.myTime.setText(_translate("MainWindow", "TextLabel"))
        self.myMission.setText(_translate("MainWindow", "TextLabel"))
        self.myBatteryLevel.setText(_translate("MainWindow", "Battery Level"))
        self.myReset.setText(_translate("MainWindow", "RESET"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.myExit.setText(_translate("MainWindow", "PushButton"))
        self.myDesc.setText(_translate("MainWindow", "TextLabel"))
#from analoggaugewidget import QRoundProgressBar
#import newrc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
